# Demo: `ForecastingAssistant.compare()`

`compare()` backtests several forecaster/estimator configurations with the **same**
cross-validation strategy and returns a metric-ranked leaderboard, plus the winning
configuration as a reusable `BacktestResult`.

Key points:

- The dataset is profiled once and the profile is shared across every candidate.
- Each candidate goes through the existing `plan()` -> `backtest()` path, so every
  row carries a reproducible `code`.
- Ranking is a pure ascending metric sort (lower is better). The LLM is never involved.
- A failing candidate is recorded in the results table and sorted last; it never
  aborts the whole comparison.

This notebook covers a **single-series** example (`h2o`) and a **multi-series**
example (`items_sales`).

## Setup

In [28]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

import numpy as np
import pandas as pd
import skforecast
import skforecast_ai

print(skforecast.__version__)
print(skforecast_ai.__version__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/Users/javier.escobar/code/github/skforecast-ai
0.23.0
0.2.0

In [29]:
import os

from skforecast.datasets import fetch_dataset
from skforecast.model_selection import TimeSeriesFold

from skforecast_ai import ForecastingAssistant

LLM_MODEL = "google:gemini-3-flash-preview"
api_key = os.getenv("GOOGLE_API_KEY")

assistant = ForecastingAssistant(
    llm=LLM_MODEL, api_key=api_key, send_data_to_llm=False
)

## 1. Single-series example (`h2o`)

Monthly expenditure on corticosteroid drugs. The raw dataset has a target column
`y` and a timestamp column `datetime`.

In [30]:
data = fetch_dataset(
    name="h2o", raw=True, kwargs_read={"names": ["y", "datetime"], "header": 0}
)
data.head()

╭────────────────────────────────────── h2o ───────────────────────────────────────╮
│ Description:                                                                     │
│ Monthly expenditure ($AUD) on corticosteroid drugs that the Australian health    │
│ system had between 1991 and 2008.                                                │
│                                                                                  │
│ Source:                                                                          │
│ Hyndman R (2023). fpp3: Data for Forecasting: Principles and Practice(3rd        │
│ Edition). http://pkg.robjhyndman.com/fpp3package/,https://github.com/robjhyndman │
│ /fpp3package, http://OTexts.com/fpp3.                                            │
│                                                                                  │
│ URL:                                                                             │
│ https://raw.githubusercontent.com/skforecast/skforecast-                         │
│ datasets/main/data/h2o.csv                                                       │
│                                                                                  │
│ Shape: 204 rows x 2 columns                                                      │
╰──────────────────────────────────────────────────────────────────────────────────╯

          y    datetime
0  0.429795  1991-07-01
1  0.400906  1991-08-01
2  0.432159  1991-09-01
3  0.492543  1991-10-01
4  0.502369  1991-11-01

### Explicit candidate configurations

Each candidate is a `(name, config)` tuple. The `config` dict accepts the same
override keys as `plan()`: `forecaster`, `estimator`, `estimator_kwargs`, `lags`,
and `window_features`.

All candidates are evaluated with the same `TimeSeriesFold`.

In [31]:
cv = TimeSeriesFold(steps=12, initial_train_size=180, refit=False)

candidates = [
    (
        "recursive_hgb",
        {
            "forecaster": "ForecasterRecursive",
            "estimator": "HistGradientBoostingRegressor",
        },
    ),
    (
        "recursive_ridge",
        {"forecaster": "ForecasterRecursive", "estimator": "Ridge"},
    ),
    (
        "direct_ridge",
        {
            "forecaster": "ForecasterDirect",
            "estimator": "Ridge",
            "lags": [1, 2, 3, 12],
        },
    ),
    (
        "foundation",
        {
            "forecaster": "ForecasterFoundation",
            # "estimator_kwargs": {"device_map": "cpu"},
        },
    ),
]

comparison = assistant.compare(
    data=data,
    cv=cv,
    target="y",
    date_column="datetime",
    candidates=candidates,
    metric=["mean_absolute_scaled_error", "mean_absolute_error"],
)

comparison

Comparing forecasters:   0%|          | 0/4 [00:00<?, ?it/s]

╭───────────────────────────────────── Explanation ──────────────────────────────────────╮
│                                                                                        │
│  Compared 4 configurations, ranked ascending by mean_absolute_scaled_error. Shared     │
│  cross-validation strategy: Using 88% of data (180 observations) for initial           │
│  training, fixed window, no refit, 12-step horizon, 2 folds. Best: 'foundation'        │
│  (ForecasterFoundation / Chronos-2) = 0.5553, 10.1% ahead of 'recursive_hgb'           │
│  (0.6179).                                                                             │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
                                    Comparison Results
┏━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Index ┃ rank ┃         name ┃   forecaster ┃    estimator ┃ mean_absol… ┃ mean_absolu… ┃
┡━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ 0     │    1 │   foundation │ ForecasterF… │    Chronos-2 │      0.5553 │       0.0543 │
├───────┼──────┼──────────────┼──────────────┼──────────────┼─────────────┼──────────────┤
│ 1     │    2 │ recursive_h… │ ForecasterR… │ HistGradien… │      0.6179 │       0.0607 │
├───────┼──────┼──────────────┼──────────────┼──────────────┼─────────────┼──────────────┤
│ 2     │    3 │ recursive_r… │ ForecasterR… │        Ridge │      0.6732 │       0.0662 │
├───────┼──────┼──────────────┼──────────────┼──────────────┼─────────────┼──────────────┤
│ 3     │    4 │ direct_ridge │ ForecasterD… │        Ridge │      0.9360 │       0.0920 │
└───────┴──────┴──────────────┴──────────────┴──────────────┴─────────────┴──────────────┘

### The ranked leaderboard

`results` is the ranked comparison table, one row per candidate, sorted best to
worst by `ranking_metric` (the first metric passed).

In [32]:
print("Ranking metric:", comparison.ranking_metric)
comparison.results

Ranking metric: mean_absolute_scaled_error

,rank,name,forecaster,estimator,mean_absolute_scaled_error,mean_absolute_error
0,1,foundation,ForecasterFoundation,Chronos-2,0.555307,0.054258
1,2,recursive_hgb,ForecasterRecursive,HistGradientBoostingRegressor,0.617946,0.060738
2,3,recursive_ridge,ForecasterRecursive,Ridge,0.673156,0.066164
3,4,direct_ridge,ForecasterDirect,Ridge,0.936035,0.092003

### Inspect the winning configuration

`best_candidate` is the top-ranked candidate as a full `BacktestResult`, carrying
its `profile`, `plan`, `metrics`, and reproducible `code`. `best_name` is its name.

In [33]:
best = comparison.best_candidate

print("Best name       :", comparison.best_name)
print("Best forecaster :", best.plan.forecaster)
print("Best estimator  :", best.plan.estimator)
print("Lags            :", best.plan.forecaster_kwargs.get("lags"))
best.metrics

Best name       : foundation
Best forecaster : ForecasterFoundation
Best estimator  : Chronos-2
Lags            : None

   mean_absolute_scaled_error  mean_absolute_error
0                    0.555307             0.054258

In [34]:
# Exact, runnable script for the winning configuration
print(best.code)

import pandas as pd
from skforecast.foundation import FoundationModel, ForecasterFoundation
from skforecast.model_selection import TimeSeriesFold, backtesting_foundation

# Load data
data = pd.read_csv('data.csv')

data['datetime'] = pd.to_datetime(data['datetime'])
data = data.set_index('datetime')
data = data.asfreq('MS')
data = data.sort_index()

# Create foundation model (chronos-2-small)
estimator = FoundationModel(
    model_id       = 'autogluon/chronos-2-small',
    context_length = 8192,
)

# Create forecaster
forecaster = ForecasterFoundation(estimator=estimator)

# Time series cross-validation configuration
cv = TimeSeriesFold(
    steps              = 12,
    initial_train_size = 180,
    refit              = False,
)

# Run backtesting
metrics, predictions = backtesting_foundation(
    forecaster        = forecaster,
    series            = data['y'],
    cv                = cv,
    metric            = ['mean_absolute_scaled_error', 'mean_absolute_error'],
    verbose           = False,
    show_progress     = True,
    suppress_warnings = True,
)

print(metrics)
print(predictions.head())

In [35]:
# Every successful candidate, keyed by name and ordered best to worst
comparison.candidates["recursive_hgb"]

╭───────────────────────────────────── Explanation ──────────────────────────────────────╮
│                                                                                        │
│  Using 88% of data (180 observations) for initial training, fixed window, no refit,    │
│  12-step horizon, 2 folds. Results — mean_absolute_scaled_error: 0.6179,               │
│  mean_absolute_error: 0.0607.                                                          │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
Cross-Validation Configuration
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Parameter          ┃ Value ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ steps              │    12 │
├────────────────────┼───────┤
│ initial_train_size │   180 │
├────────────────────┼───────┤
│ refit              │ False │
├────────────────────┼───────┤
│ fixed_train_size   │  True │
├────────────────────┼───────┤
│ gap                │     0 │
├────────────────────┼───────┤
│ fold_stride        │    12 │
├────────────────────┼───────┤
│ differentiation    │  None │
├────────────────────┼───────┤
│ n_folds            │     2 │
└────────────────────┴───────┘
                  Backtest Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ mean_absolute_scaled_error ┃ mean_absolute_error ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│                     0.6179 │              0.0607 │
└────────────────────────────┴─────────────────────┘
     Backtest Predictions (24 rows)
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┓
┃ Index               ┃   fold ┃   pred ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━┩
│ 2006-07-01 00:00:00 │ 0.0000 │ 0.8825 │
├─────────────────────┼────────┼────────┤
│ 2006-08-01 00:00:00 │ 0.0000 │ 0.9903 │
├─────────────────────┼────────┼────────┤
│ 2006-09-01 00:00:00 │ 0.0000 │ 1.0627 │
├─────────────────────┼────────┼────────┤
│ 2006-10-01 00:00:00 │ 0.0000 │ 1.1247 │
├─────────────────────┼────────┼────────┤
│ 2006-11-01 00:00:00 │ 0.0000 │ 1.1628 │
├─────────────────────┼────────┼────────┤
│ ...                 │    ... │    ... │
├─────────────────────┼────────┼────────┤
│ 2008-02-01 00:00:00 │ 1.0000 │ 0.5889 │
├─────────────────────┼────────┼────────┤
│ 2008-03-01 00:00:00 │ 1.0000 │ 0.6831 │
├─────────────────────┼────────┼────────┤
│ 2008-04-01 00:00:00 │ 1.0000 │ 0.5963 │
├─────────────────────┼────────┼────────┤
│ 2008-05-01 00:00:00 │ 1.0000 │ 0.7781 │
├─────────────────────┼────────┼────────┤
│ 2008-06-01 00:00:00 │ 1.0000 │ 0.8077 │
└─────────────────────┴────────┴────────┘
      Dataset Profile
┏━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ Property       ┃ Value  ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ Format         │ single │
├────────────────┼────────┤
│ Series         │ 1      │
├────────────────┼────────┤
│ Observations   │ 204    │
├────────────────┼────────┤
│ Frequency      │ MS     │
├────────────────┼────────┤
│ Target         │ y      │
├────────────────┼────────┤
│ Exog columns   │ none   │
├────────────────┼────────┤
│ Missing target │ none   │
└────────────────┴────────┘

                                      Recommendation
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Property              ┃ Value                                                          ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Task type             │ single_series                                                  │
├───────────────────────┼────────────────────────────────────────────────────────────────┤
│ Forecaster            │ ForecasterRecursive                                            │
├───────────────────────┼────────────────────────────────────────────────────────────────┤
│ Forecaster candidates │ ForecasterRecursive, ForecasterDirect, ForecasterFoundation,   │
│                       │ ForecasterStats                                                │
├───────────────────────┼────────────────────────────────────────────────────────────────┤
│ Estimator             │ Ridge                                                          │
├───────────────────────┼────────────────────────────────────────────────────────────────┤
│ Estimator candidates  │ Ridge, RandomForestRegressor, LGBMRegressor                    │
└───────────────────────┴────────────────────────────────────────────────────────────────┘

╭───────────────────────────────────── Explanation ──────────────────────────────────────╮
│                                                                                        │
│  A single-series ML forecaster (ForecasterRecursive) is recommended. Data: 204         │
│  observations, 'MS' frequency. Alternative forecasters: ['ForecasterDirect',           │
│  'ForecasterFoundation', 'ForecasterStats']. Estimator: Ridge. A linear model is       │
│  preferred because the dataset is small (204 observations < 250); gradient boosting    │
│  is offered as an alternative once more data is available. Alternative estimators:     │
│  ['RandomForestRegressor', 'LGBMRegressor'].                                           │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
                                      Forecast Plan
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Property          ┃ Value                                                              ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Forecaster        │ ForecasterRecursive                                                │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Estimator         │ HistGradientBoostingRegressor                                      │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Steps             │ 12                                                                 │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Frequency         │ MS                                                                 │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Lags              │ [1, 9, 10, 11, 12, 13, 14]                                         │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Window features   │ [{'stats': ['mean', 'std'], 'window_size': 3}, {'stats': ['mean'], │
│                   │ 'window_size': 12}, {'stats': ['mean'], 'window_size': 36}]        │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Calendar features │ ['month', 'quarter'] (raw ordinal encoding)                        │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Use exog          │ False                                                              │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Interval          │ none                                                               │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Interval method   │ N/A                                                                │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Primary metric    │ mean_absolute_scaled_error                                         │
├───────────────────┼────────────────────────────────────────────────────────────────────┤
│ Preprocessing     │ none                                                               │
└───────────────────┴────────────────────────────────────────────────────────────────────┘

╭─────────────────────────────────── Plan Explanation ───────────────────────────────────╮
│                                                                                        │
│  Plan: ForecasterRecursive + HistGradientBoostingRegressor. Lags: [1, 9, 10, 11, 12,   │
│  13, 14]. Window features: ['mean(window=3)', 'std(window=3)', 'mean(window=12)',      │
│  'mean(window=36)']. Calendar features: ['month', 'quarter'] (raw ordinal encoding).   │
│  NaN rows kept (NaN-tolerant estimator). MAE is interpretable, robust to outliers,     │
│  and works at any scale.                                                               │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
───────────────────────────────────── Generated code ─────────────────────────────────────
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from skforecast.preprocessing import RollingFeatures, CalendarFeatures
from skforecast.recursive import ForecasterRecursive
from skforecast.model_selection import TimeSeriesFold, backtesting_forecaster

# Load data
data = pd.read_csv('data.csv')

data['datetime'] = pd.to_datetime(data['datetime'])
data = data.set_index('datetime')
data = data.asfreq('MS')
data = data.sort_index()

window_features = RollingFeatures(
    stats        = ['mean', 'std', 'mean', 'mean'],
    window_sizes = [3, 3, 12, 36],
)

calendar_features = CalendarFeatures(
    features = ['month', 'quarter'],
    encoding = None,
)

# Create forecaster
forecaster = ForecasterRecursive(
    estimator            = HistGradientBoostingRegressor(random_state=123),
    lags                 = [1, 9, 10, 11, 12, 13, 14],
    window_features      = window_features,
    calendar_features    = calendar_features,
    categorical_features = 'auto',
    dropna_from_series   = False,
)

# Time series cross-validation configuration
cv = TimeSeriesFold(
    steps              = 12,
    initial_train_size = 180,
    refit              = False,
)

# Run backtesting
metrics, predictions = backtesting_forecaster(
    forecaster        = forecaster,
    y                 = data['y'],
    cv                = cv,
    metric            = ['mean_absolute_scaled_error', 'mean_absolute_error'],
    n_jobs            = 'auto',
    verbose           = False,
    show_progress     = True,
    suppress_warnings = True,
)

print(metrics)
print(predictions.head())

### Reuse the winner in other methods

Because the winning configuration is a full `BacktestResult`, its `profile` and
`plan` flow straight into `forecast()` (or `backtest()`, `forecast_code()`) with
no extra plumbing.

In [36]:
forecast = assistant.forecast(
    data=data,
    steps=12,
    target="y",
    date_column="datetime",
    profile=best.profile,
    plan=best.plan,
)

forecast.predictions

           level      pred
2008-07-01     y  1.002536
2008-08-01     y  1.030961
2008-09-01     y  1.083664
2008-10-01     y  1.184066
2008-11-01     y  1.170530
2008-12-01     y  1.280745
2009-01-01     y  1.280523
2009-02-01     y  0.682301
2009-03-01     y  0.791058
2009-04-01     y  0.760868
2009-05-01     y  0.843517
2009-06-01     y  0.912067

### Zero-configuration comparison (`candidates=None`)

When `candidates` is omitted, the candidate set is built automatically from
`profile.forecaster_candidates`, each paired with its recommended estimator. This
gives a call that "just works".

Note: the auto set may include foundation and statistical forecasters, which
require their optional backends. Any candidate whose backend is missing is
recorded in the `error` column and ranked last instead of aborting the run.

In [37]:
comparison_auto = assistant.compare(
    data=data,
    cv=cv,
    target="y",
    date_column="datetime",
)

comparison_auto.results

Comparing forecasters:   0%|          | 0/4 [00:00<?, ?it/s]

,rank,name,forecaster,estimator,mean_absolute_error,mean_squared_error,mean_absolute_scaled_error,mean_absolute_percentage_error
0,1,ForecasterFoundation,ForecasterFoundation,Chronos-2,0.054258,0.004661,0.555307,0.063092
1,2,ForecasterStats,ForecasterStats,Arima,0.057430,0.005372,0.587772,0.068537
2,3,ForecasterRecursive,ForecasterRecursive,Ridge,0.066164,0.006713,0.673156,0.077519
3,4,ForecasterDirect,ForecasterDirect,Ridge,0.088894,0.014046,0.904409,0.107168

In [38]:
type(comparison_auto)

skforecast_ai.schemas.results.ComparisonResult

### Ask about the results

In [39]:
# Asking the assistant about the comparison results
# ==============================================================================
explanation = assistant.ask(
    prompt = "Explain the results of the comparison, why the best forecaster was selected, and what are the next steps.",
    result = comparison_auto
)

In [40]:
explanation.explanation

'The ForecasterFoundation using the Chronos-2 model is the top-performing configuration for this monthly dataset, achieving a mean_absolute_error of 0.054258. This model outperformed statistical approaches and machine learning models trained on the 204 available observations.\n\n## Comparison Results\n\nThe evaluation compared four different forecasting strategies using a cross-validation process with 2 folds, a 12-step horizon, and an initial training size of 180 observations.\n\n*   ForecasterFoundation (Chronos-2): Rank 1, MAE 0.054258. Its mean_absolute_scaled_error of 0.555307 indicates it beats the naive baseline.\n*   ForecasterStats (Arima): Rank 2, MAE 0.057430.\n*   ForecasterRecursive (Ridge): Rank 3, MAE 0.066164.\n*   ForecasterDirect (Ridge): Rank 4, MAE 0.088894.\n\nThe deterministic summary notes that the winning ForecasterFoundation is 5.5% ahead of the ForecasterStats candidate. All candidates achieved a mean_absolute_scaled_error below 1, which confirms they are more accurate than a naive seasonal baseline.\n\n## Selection Rationale\n\nThe ForecasterFoundation was selected as the winner because it achieved the lowest mean_absolute_error among all evaluated candidates. This metric was chosen for the plan because it is interpretable and robust to outliers. The selection process follows a deterministic ascending sort of the primary metric where lower values represent higher accuracy. While a linear Ridge model was initially recommended for this small dataset of 204 observations, the pre-trained foundation model provided superior results in this comparison.\n\n## Next Steps\n\nTo further improve or build upon these results, consider the following actions:\n\n*   Use bayesian_search_forecaster to optimize the hyperparameters of the Ridge estimator or to explore the LGBMRegressor alternative mentioned in the profile decision.\n*   Generate uncertainty quantification for the winning model by calling the predict_interval method.\n*   If more data becomes available, use backtesting_forecaster with refit set to True to evaluate how the models adapt to new observations over time.\n*   Explore feature engineering for the recursive models by adding RollingFeatures to capture trends or volatility that the Ridge estimator may not identify on its own.'

In [41]:
explanation

╭────────────────────────────────── Assistant Response ──────────────────────────────────╮
│                                                                                        │
│  The ForecasterFoundation using the Chronos-2 model is the top-performing              │
│  configuration for this monthly dataset, achieving a mean_absolute_error of 0.054258.  │
│  This model outperformed statistical approaches and machine learning models trained    │
│  on the 204 available observations.                                                    │
│                                                                                        │
│  Comparison Results                                                                    │
│                                                                                        │
│  The evaluation compared four different forecasting strategies using a                 │
│  cross-validation process with 2 folds, a 12-step horizon, and an initial training     │
│  size of 180 observations.                                                             │
│                                                                                        │
│   • ForecasterFoundation (Chronos-2): Rank 1, MAE 0.054258. Its                        │
│     mean_absolute_scaled_error of 0.555307 indicates it beats the naive baseline.      │
│   • ForecasterStats (Arima): Rank 2, MAE 0.057430.                                     │
│   • ForecasterRecursive (Ridge): Rank 3, MAE 0.066164.                                 │
│   • ForecasterDirect (Ridge): Rank 4, MAE 0.088894.                                    │
│                                                                                        │
│  The deterministic summary notes that the winning ForecasterFoundation is 5.5% ahead   │
│  of the ForecasterStats candidate. All candidates achieved a                           │
│  mean_absolute_scaled_error below 1, which confirms they are more accurate than a      │
│  naive seasonal baseline.                                                              │
│                                                                                        │
│  Selection Rationale                                                                   │
│                                                                                        │
│  The ForecasterFoundation was selected as the winner because it achieved the lowest    │
│  mean_absolute_error among all evaluated candidates. This metric was chosen for the    │
│  plan because it is interpretable and robust to outliers. The selection process        │
│  follows a deterministic ascending sort of the primary metric where lower values       │
│  represent higher accuracy. While a linear Ridge model was initially recommended for   │
│  this small dataset of 204 observations, the pre-trained foundation model provided     │
│  superior results in this comparison.                                                  │
│                                                                                        │
│  Next Steps                                                                            │
│                                                                                        │
│  To further improve or build upon these results, consider the following actions:       │
│                                                                                        │
│   • Use bayesian_search_forecaster to optimize the hyperparameters of the Ridge        │
│     estimator or to explore the LGBMRegressor alternative mentioned in the profile     │
│     decision.                                                                          │
│   • Generate uncertainty quantification for the winning model by calling the           │
│     predict_interval method.                                                           │
│   • If more data becomes available, use backtesting_forecaster with refit set to True  │
│     to evaluate how the models adapt to new observations over time.                    │
│   • Explore feature engineering for the recursive models by adding RollingFeatures to  │
│     capture trends or volatility that the Ridge estimator may not identify on its      │
│     own.                                                                               │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
───────────────────────────────────── Generated code ─────────────────────────────────────
import pandas as pd
from skforecast.foundation import FoundationModel, ForecasterFoundation
from skforecast.model_selection import TimeSeriesFold, backtesting_foundation

# Load data
data = pd.read_csv('data.csv')

data['datetime'] = pd.to_datetime(data['datetime'])
data = data.set_index('datetime')
data = data.asfreq('MS')
data = data.sort_index()

# Create foundation model (chronos-2-small)
estimator = FoundationModel(
    model_id       = 'autogluon/chronos-2-small',
    context_length = 8192,
)

# Create forecaster
forecaster = ForecasterFoundation(estimator=estimator)

# Time series cross-validation configuration
cv = TimeSeriesFold(
    steps              = 12,
    initial_train_size = 180,
    refit              = False,
)

# Run backtesting
metrics, predictions = backtesting_foundation(
    forecaster        = forecaster,
    series            = data['y'],
    cv                = cv,
    metric            = ['mean_absolute_error', 'mean_squared_error',
'mean_absolute_scaled_error', 'mean_absolute_percentage_error'],
    verbose           = False,
    show_progress     = True,
    suppress_warnings = True,
)

print(metrics)
print(predictions.head())

## 2. Multi-series example (`items_sales`)

Simulated daily sales for 3 items in wide format (one column per series, indexed
by date). For multi-series tasks the leaderboard ranks candidates using the pooled
`average` metric across series.

In [15]:
data = fetch_dataset(name="items_sales")
data.head()

╭─────────────────────── items_sales ───────────────────────╮
│ Description:                                              │
│ Simulated time series for the sales of 3 different items. │
│                                                           │
│ Source:                                                   │
│ Simulated data.                                           │
│                                                           │
│ URL:                                                      │
│ https://raw.githubusercontent.com/skforecast/skforecast-  │
│ datasets/main/data/simulated_items_sales.csv              │
│                                                           │
│ Shape: 1097 rows x 3 columns                              │
╰───────────────────────────────────────────────────────────╯

               item_1     item_2     item_3
date
2012-01-01   8.253175  21.047727  19.429739
2012-01-02  22.777826  26.578125  28.009863
2012-01-03  27.549099  31.751042  32.078922
2012-01-04  25.895533  24.567708  27.252276
2012-01-05  21.379238  18.191667  20.357737

In [16]:
cv = TimeSeriesFold(steps=30, initial_train_size=900, refit=False)

candidates = [
    (
        "multiseries_lgbm",
        {"forecaster": "ForecasterRecursiveMultiSeries", "estimator": "LGBMRegressor"},
    ),
    (
        "multiseries_hgb",
        {
            "forecaster": "ForecasterRecursiveMultiSeries",
            "estimator": "HistGradientBoostingRegressor",
        },
    ),
]

comparison_ms = assistant.compare(
    data=data,
    cv=cv,
    target=["item_1", "item_2", "item_3"],
    candidates=candidates,
)

comparison_ms

Comparing forecasters:   0%|          | 0/2 [00:00<?, ?it/s]

╭───────────────────────────────────── Explanation ──────────────────────────────────────╮
│                                                                                        │
│  Compared 2 configurations, ranked ascending by mean_absolute_scaled_error pooled      │
│  across series. Shared cross-validation strategy: Using 82% of data (900               │
│  observations) for initial training, fixed window, no refit, 30-step horizon, 7        │
│  folds. Best: 'multiseries_lgbm' (ForecasterRecursiveMultiSeries / LGBMRegressor) =    │
│  0.8422, 1.9% ahead of 'multiseries_hgb' (0.8581).                                     │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
                                    Comparison Results
┏━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┓
┃ Index ┃ rank ┃     name ┃ forecas… ┃ estima… ┃ mean_ab… ┃ mean_s… ┃ mean_ab… ┃ mean_a… ┃
┡━━━━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━┩
│ 0     │    1 │ multise… │ Forecas… │ LGBMRe… │   2.1714 │  9.2802 │   0.8422 │  0.1403 │
├───────┼──────┼──────────┼──────────┼─────────┼──────────┼─────────┼──────────┼─────────┤
│ 1     │    2 │ multise… │ Forecas… │ HistGr… │   2.1792 │  9.0634 │   0.8581 │  0.1408 │
└───────┴──────┴──────────┴──────────┴─────────┴──────────┴─────────┴──────────┴─────────┘

In [17]:
print("Ranking metric:", comparison_ms.ranking_metric)
comparison_ms.results

Ranking metric: mean_absolute_scaled_error

,rank,name,forecaster,estimator,mean_absolute_error,mean_squared_error,mean_absolute_scaled_error,mean_absolute_percentage_error
0,1,multiseries_lgbm,ForecasterRecursiveMultiSeries,LGBMRegressor,2.17144,9.280169,0.842207,0.140330
1,2,multiseries_hgb,ForecasterRecursiveMultiSeries,HistGradientBoostingRegressor,2.17925,9.063407,0.858122,0.140804

In [18]:
best_ms = comparison_ms.best_candidate

print("Best forecaster:", best_ms.plan.forecaster)
print("Best estimator :", best_ms.plan.estimator)
best_ms.metrics

Best forecaster: ForecasterRecursiveMultiSeries
Best estimator : LGBMRegressor

,levels,mean_absolute_error,mean_squared_error,mean_absolute_scaled_error,mean_absolute_percentage_error
0,item_1,1.090163,2.743062,0.708829,0.053895
1,item_2,2.379341,9.007092,1.000835,0.162188
2,item_3,3.044815,16.090354,0.816957,0.204908
3,average,2.171440,9.280169,0.842207,0.140330
4,weighted_average,2.171440,9.280169,0.842207,0.140330
5,pooling,2.171440,9.280169,0.852397,0.140330

### Ask about comparison results

In [19]:
# Asking the assistant about the comparison results
# ==============================================================================
explanation = assistant.ask(
    prompt = "Explain the results of the comparison, why the best forecaster was selected, and what are the next steps.",
    result = comparison_ms
)

/var/folders/wt/8tvn563d5v55nspfbydgqb9r0000gp/T/ipykernel_37051/2697241421.py:3: DataSentToLLMWarning: `send_data_to_llm=False` is overridden when `result` is passed to `ask()`: the predicted values carried by the result are sent to the LLM, because a question about a result cannot be answered from summary statistics alone. The dataset the result was produced from is never sent. To keep predicted values local, ask without `result`.
  explanation = assistant.ask(

In [20]:
explanation.explanation

'The comparison of multi-series forecasting models identified the `multiseries_lgbm` configuration as the most accurate for predicting the three daily item series. This candidate was selected because it achieved the lowest Mean Absolute Scaled Error (MASE) across the evaluated folds.\n\n## Comparison Results\n\nThe evaluation compared two configurations using a global `ForecasterRecursiveMultiSeries` approach, which trains a single model to forecast all series simultaneously.\n\n*   The winning candidate, `multiseries_lgbm`, produced a MASE of 0.842207, a Mean Absolute Error (MAE) of 2.17144, and a Mean Absolute Percentage Error (MAPE) of 0.140330.\n*   The runner-up, `multiseries_hgb`, followed with a MASE of 0.858122.\n*   The deterministic summary indicates the winner is 1.9 percent ahead of the runner-up in terms of the primary ranking metric.\n*   Both candidates achieved a MASE below 1, which signifies that they both outperformed the naive baseline.\n\n## Why the Winning Forecaster was Selected\n\nThe `multiseries_lgbm` candidate was selected based on a deterministic sort of the `mean_absolute_scaled_error` metric. This specific configuration uses a LightGBM estimator and incorporates several features that may contribute to its performance:\n\n*   It utilizes 7 lags and a set of rolling window features, specifically the mean and standard deviation over a 3-day window, and the mean over 7-day and 21-day windows.\n*   The plan includes calendar features such as the day of the week, weekend indicators, and the month, which are associated with capturing recurring daily and monthly patterns.\n*   The choice of MASE as the ranking metric allowed for a scale-independent comparison, which is useful when evaluating multiple series like `item_1`, `item_2`, and `item_3` that may have different volume levels.\n\nThe model was validated using a backtesting strategy with 7 folds and a 30-step forecast horizon, ensuring the performance metrics are representative of multi-step forecasting requirements.\n\n## Next Steps\n\nTo further refine the forecasting process, the following steps are suggested using the skforecast API:\n\n*   Perform hyperparameter optimization using `bayesian_search_forecaster` to find more effective settings for the LightGBM estimator and the lag selection.\n*   Incorporate uncertainty quantification by using the `predict_interval` method to generate probabilistic forecasts.\n*   Explore feature selection with `select_features_multiseries` to determine if any of the rolling or calendar features can be simplified without losing accuracy.\n*   If the relationship between series changes significantly over the 30-day horizon, consider testing `ForecasterDirectMultiVariate` to see if a step-specific modeling approach improves the results.'

In [21]:
explanation

╭────────────────────────────────── Assistant Response ──────────────────────────────────╮
│                                                                                        │
│  The comparison of multi-series forecasting models identified the multiseries_lgbm     │
│  configuration as the most accurate for predicting the three daily item series. This   │
│  candidate was selected because it achieved the lowest Mean Absolute Scaled Error      │
│  (MASE) across the evaluated folds.                                                    │
│                                                                                        │
│  Comparison Results                                                                    │
│                                                                                        │
│  The evaluation compared two configurations using a global                             │
│  ForecasterRecursiveMultiSeries approach, which trains a single model to forecast all  │
│  series simultaneously.                                                                │
│                                                                                        │
│   • The winning candidate, multiseries_lgbm, produced a MASE of 0.842207, a Mean       │
│     Absolute Error (MAE) of 2.17144, and a Mean Absolute Percentage Error (MAPE) of    │
│     0.140330.                                                                          │
│   • The runner-up, multiseries_hgb, followed with a MASE of 0.858122.                  │
│   • The deterministic summary indicates the winner is 1.9 percent ahead of the         │
│     runner-up in terms of the primary ranking metric.                                  │
│   • Both candidates achieved a MASE below 1, which signifies that they both            │
│     outperformed the naive baseline.                                                   │
│                                                                                        │
│  Why the Winning Forecaster was Selected                                               │
│                                                                                        │
│  The multiseries_lgbm candidate was selected based on a deterministic sort of the      │
│  mean_absolute_scaled_error metric. This specific configuration uses a LightGBM        │
│  estimator and incorporates several features that may contribute to its performance:   │
│                                                                                        │
│   • It utilizes 7 lags and a set of rolling window features, specifically the mean     │
│     and standard deviation over a 3-day window, and the mean over 7-day and 21-day     │
│     windows.                                                                           │
│   • The plan includes calendar features such as the day of the week, weekend           │
│     indicators, and the month, which are associated with capturing recurring daily     │
│     and monthly patterns.                                                              │
│   • The choice of MASE as the ranking metric allowed for a scale-independent           │
│     comparison, which is useful when evaluating multiple series like item_1, item_2,   │
│     and item_3 that may have different volume levels.                                  │
│                                                                                        │
│  The model was validated using a backtesting strategy with 7 folds and a 30-step       │
│  forecast horizon, ensuring the performance metrics are representative of multi-step   │
│  forecasting requirements.                                                             │
│                                                                                        │
│  Next Steps                                                                            │
│                                                                                        │
│  To further refine the forecasting process, the following steps are suggested using    │
│  the skforecast API:                                                                   │
│                                                                                        │
│   • Perform hyperparameter optimization using bayesian_search_forecaster to find more  │
│     effective settings for the LightGBM estimator and the lag selection.               │
│   • Incorporate uncertainty quantification by using the predict_interval method to     │
│     generate probabilistic forecasts.                                                  │
│   • Explore feature selection with select_features_multiseries to determine if any of  │
│     the rolling or calendar features can be simplified without losing accuracy.        │
│   • If the relationship between series changes significantly over the 30-day horizon,  │
│     consider testing ForecasterDirectMultiVariate to see if a step-specific modeling   │
│     approach improves the results.                                                     │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯
───────────────────────────────────── Generated code ─────────────────────────────────────
import pandas as pd
from lightgbm import LGBMRegressor
from skforecast.preprocessing import RollingFeatures, CalendarFeatures
from skforecast.recursive import ForecasterRecursiveMultiSeries
from skforecast.model_selection import TimeSeriesFold, backtesting_forecaster_multiseries

# Load data
data = pd.read_csv('data.csv', index_col=0, parse_dates=True)

data = data.asfreq('D')
data = data.sort_index()

window_features = RollingFeatures(
    stats        = ['mean', 'std', 'mean', 'mean'],
    window_sizes = [3, 3, 7, 21],
)

calendar_features = CalendarFeatures(
    features = ['day_of_week', 'weekend', 'month'],
    encoding = None,
)

# Create forecaster
forecaster = ForecasterRecursiveMultiSeries(
    estimator            = LGBMRegressor(random_state=123, verbose=-1),
    lags                 = 7,
    window_features      = window_features,
    calendar_features    = calendar_features,
    encoding             = 'ordinal',
    categorical_features = 'auto',
    dropna_from_series   = False,
)

# Time series cross-validation configuration
cv = TimeSeriesFold(
    steps              = 30,
    initial_train_size = 900,
    refit              = False,
)

# Run backtesting
metrics, predictions = backtesting_forecaster_multiseries(
    forecaster        = forecaster,
    series            = data[['item_1', 'item_2', 'item_3']],
    cv                = cv,
    metric            = ['mean_absolute_error', 'mean_squared_error',
'mean_absolute_scaled_error', 'mean_absolute_percentage_error'],
    n_jobs            = 'auto',
    verbose           = False,
    show_progress     = True,
    suppress_warnings = True,
)

print(metrics)
print(predictions.head())

## Errors

### Partial fail

In [22]:
import warnings
import numpy as np, pandas as pd
from skforecast.model_selection import TimeSeriesFold
from skforecast_ai import ForecastingAssistant, AllCandidatesFailedError, CandidateFailedWarning

rng = np.random.default_rng(123)
data = pd.DataFrame({
    "date": pd.date_range("2020-01-01", periods=120, freq="D"),
    "sales": 100 + np.arange(120) * 0.5 + rng.normal(0, 5, 120),
})
assistant = ForecastingAssistant()
cv = TimeSeriesFold(steps=5, initial_train_size=90, verbose=False)

result = assistant.compare(
    data=data, cv=cv, target="sales", date_column="date",
    candidates=[
        ("good_recursive", {"forecaster": "ForecasterRecursive"}),
        ("good_ridge",     {"forecaster": "ForecasterDirect", "estimator": "Ridge"}),
        ("bad",            {"forecaster": "ForecasterRecursive", "estimator": "NotAReal"}),
    ],
    show_progress=False,
)

/var/folders/wt/8tvn563d5v55nspfbydgqb9r0000gp/T/ipykernel_37051/2583135104.py:14: CandidateFailedWarning: Candidate 'bad' failed and is ranked last: ImportError: cannot import name 'NotAReal' from '__main__' (unknown location). The full traceback is available in `ComparisonResult.failures['bad'].traceback`.
  result = assistant.compare(

In [23]:
result.results

,rank,name,forecaster,estimator,mean_absolute_error,mean_squared_error,mean_absolute_scaled_error,mean_absolute_percentage_error,error
0,1,good_ridge,ForecasterDirect,Ridge,4.833609,33.65461,1.084619,0.031755,None
1,2,good_recursive,ForecasterRecursive,Ridge,5.147115,37.61593,1.154966,0.033681,None
2,3,bad,ForecasterRecursive,NotAReal,NaN,NaN,NaN,NaN,ImportError: cannot import name 'NotAReal' fro...

In [24]:
f = result.failures["bad"]
print(f.error_type)        # ImportError
print(f.summary())         # ImportError: cannot import name 'NotAReal' ...
print(f.traceback)         # full traceback, points at <backtesting> line 3
print(f.generated_code)    # the exact 1723-char script that failed

ImportError
ImportError: cannot import name 'NotAReal' from '__main__' (unknown location)
Traceback (most recent call last):
  File "/Users/javier.escobar/code/github/skforecast-ai/skforecast_ai/execution/backtesting_runner.py", line 174, in _exec_rendered_code
    exec(compiled, namespace)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<backtesting>", line 3, in <module>
ImportError: cannot import name 'NotAReal' from '__main__' (unknown location)

import pandas as pd
from sklearn.preprocessing import StandardScaler
from __main__ import NotAReal  # TODO: replace with correct import for NotAReal
from skforecast.preprocessing import RollingFeatures, CalendarFeatures
from skforecast.recursive import ForecasterRecursive
from skforecast.model_selection import TimeSeriesFold, backtesting_forecaster

data['date'] = pd.to_datetime(data['date'])
data = data.set_index('date')
data = data.asfreq('D')
data = data.sort_index()

window_features = RollingFeatures(
    stats        = ['mean', 'std', 'mean', 'mean'],
    window_sizes = [3, 3, 7, 21],
)

calendar_features = CalendarFeatures(
    features = ['day_of_week', 'weekend', 'month'],
    encoding = 'cyclical',
)

# Create forecaster
forecaster = ForecasterRecursive(
    estimator            = NotAReal(),
    lags                 = [1, 2, 3, 4, 5, 7],
    window_features      = window_features,
    calendar_features    = calendar_features,
    transformer_y        = StandardScaler(),
    categorical_features = 'auto',
    dropna_from_series   = False,
)

# Time series cross-validation configuration
cv = TimeSeriesFold(
    steps              = 5,
    initial_train_size = 90,
    refit              = False,
)

# Run backtesting
metrics, predictions = backtesting_forecaster(
    forecaster        = forecaster,
    y                 = data['sales'],
    cv                = cv,
    metric            = ['mean_absolute_error', 'mean_squared_error', 'mean_absolute_scaled_error', 'mean_absolute_percentage_error'],
    n_jobs            = 'auto',
    verbose           = False,
    show_progress = False,
    suppress_warnings = True,
)

print(metrics)
print(predictions.head())

### Total fail

In [25]:
warnings.simplefilter("ignore")
try:
    assistant.compare(
        data=data, cv=cv, target="sales", date_column="date",
        candidates=[
            ("bad_1", {"forecaster": "ForecasterRecursive", "estimator": "NotAReal"}),
            ("bad_2", {"forecaster": "ForecasterDirect", "estimator": "AlsoNotReal"}),
        ],
        show_progress=False,
    )
except AllCandidatesFailedError as exc:
    print(exc)
    print(exc.failures["bad_1"].traceback)

All 2 candidate configuration(s) failed to run, so there is no ranking to report.

  - bad_1: ImportError: cannot import name 'NotAReal' from '__main__' (unknown location)
  - bad_2: ImportError: cannot import name 'AlsoNotReal' from '__main__' (unknown location)

Inspect a failure with `exc.failures['<name>'].traceback` or `exc.failures['<name>'].generated_code`.
Traceback (most recent call last):
  File "/Users/javier.escobar/code/github/skforecast-ai/skforecast_ai/execution/backtesting_runner.py", line 174, in _exec_rendered_code
    exec(compiled, namespace)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<backtesting>", line 3, in <module>
ImportError: cannot import name 'NotAReal' from '__main__' (unknown location)